### PR TITLE
Rewrite split algorithm and allow returning everything without pinyin list wrapping

### PR DESCRIPTION
**Pull request by T-vK**
I forked your project because I needed a way to split the pinyin in a certain way. Your project almost did it for me, but not quite, I had to make some modifications. I was just looking for a way to convert the original text input into an array of pinyin syllables and special characters (punctuation etc). 
I ended up completely rewriting your split algorithm because I figured the pinyin-utils aren't really necessary. I am declaring a lot of variables with meaningful names in the algorithm so that it becomes easier to understand.

the split function now has 3 parameters instead of two. The first one is for the text input (as before) the second one is to tell if you want to return everything (or just the pinyin) and the third one is to specify if the pinyin should be wrapped in arrays. So basically instead of `sort('ni hao ma?',true)` you now have to do `sort('ni hao ma?',true,true)` instead now. This, unfortunately,  is a "breaking change" if you will, but it made the most sense to me tbh and my intention wasn't really to make a PR. But I figured I would just create one and let you decide if you like it or not.

Offtopic:
I really like your projects btw! I've used quite a few of them recently. I wish I would have found them earlier though. It would have saved me quite some time. ;)  
I will use pinyin-split in this project btw: https://github.com/FOSS-Chinese/AnkiDeckGenerator
There is some cool stuff in the project that might be interesting to you, if you're learning Chinese.

### CODE REVIEW

**Comment by pepebecker** [comment]
@T-vK thank you for your PR! I just ran an example code using your fork and compared it to mine.

```js
console.log(split('This is random text: "wodemaoxihuanheniunai".', true, true));
```

This is the result I got by using my version:
```js
[
 'This is ', [ 'ran' ], 'd', [ 'o' ], 'm ', [ 'te' ], 'xt: "',
 [ 'wo' ], [ 'de' ], [ 'mao' ], [ 'xi' ], [ 'huan' ], [ 'he' ], [ 'niu' ], [ 'nai' ], '".'
]
```

And this is the result I got by using your fork:
```js
[
 'hi', 's', ' ', 'i', 's', ' ', [ 'ran' ], 'do', 'm', ' ', [ 'te' ],   'x',   't',   ': "',
 [ 'wo' ], [ 'de' ], [ 'mao' ], ['xi' ], [ 'huan' ], [ 'he' ], [ 'niu' ], [ 'nai' ], '".' 
]
```

As you can see there is the `T` missing from `This` in the beginning of the sentence and then there are 2 chars `'h'` and `'i'` together in one string (`'hi'`) while the following `'s'` is in a separate string which I don't really understand.

Was this done intentionally?

I checked out your AnkiDeckGenerator, looks pretty cool!

**Comment by T-vK** [comment]
No, this wasn't intentional. I just ran the mocha tests and they didn't fail so I assumed it was working as before. I'll try to fix it.

**Comment by derhuerst** [comment]
@pepebecker Consider writing a test for this case.

**Comment by T-vK** [comment]
It would have required me to make some fundamental changes to my algorithm to make it return the same result for that new test case. So I actually reverted to your old algorithm and adjusted it to not require pinyin-utils and to have that additional parameter. I also added a new test for that new case.

**Comment by pepebecker** [comment]
@T-vK @derhuerst My bad, I updated the tests now.

@T-vK I added some changes to your latest changes and created a [PR on your fork](https://github.com/T-vK/pinyin-split/pull/1), I hope it still suits your needs.

**Comment by T-vK** [comment]
@pepebecker Yes, totally. Thanks. I merged your PR.

**Pull request merged**
